### ISSUE TITLE
passing --number to image-scanner-remote triggers TB

### ISSUE THREAD

**Issue by baude** [baude/image-scanner#59]
[bbaude@localhost image-scanner]$ python image_scanner_client/image-scanner-remote.py --number 4
Traceback (most recent call last):
  File "image_scanner_client/image-scanner-remote.py", line 132, in <module>
    docker_state = remotescan._get_docker_state(scansummary)
  File "image_scanner_client/image-scanner-remote.py", line 90, in _get_docker_state
    docker_state = self.remote_client.get_docker_json(summary['json_url'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by baude** [comment]
https://github.com/baude/image-scanner/commit/6a98048051c910fc11a4404d945f248f2280dddb
