### ISSUE TITLE
return_cve_by_docker_obj fails 

### ISSUE THREAD

**Issue by ajcollins0** [baude/image-scanner#68]
I think if docker_state_file scanned a non-RHEL based image, then we will get the below error: 

Traceback (most recent call last):
  File "image_scanner_client/tester.py", line 61, in <module>
    obj = xmlp.return_cve_by_docker_obj(docker_state)
  File "/home/alcollin/Desktop/work/image-scanner/image_scanner_client/xml_parse.py", line 210, in return_cve_by_docker_obj
    cve_details = self._walk_cves(dock_pointer['cve_summary']
KeyError: 'cve_summary'

**Comment by ajcollins0** [comment]
closed by PR #69
